version: '3.8'

services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: k-curry-jib
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3308:3306"

  customer-be:
    build:
      context: ./
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/k-curry-jib
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_USERNAME=root
    restart: always
    ports:
      - "8889:8889"