server:
  port: 8889
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/kcj-db
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations: classpath:db/changelog/init-db.sql
      data-locations: classpath:db/changelog/data.sql
      mode: always

#logging:
#  level:
#    root: debug