CREATE TABLE SPRING_SESSION (
    PRIMARY_ID VARCHAR(100) PRIMARY KEY,
    SESSION_ID VARCHAR(100) UNIQUE,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(100)
);