package com.kcjcustomerbe.mapper;

import com.kcjcustomerbe.dto.ProductDto;
import com.kcjcustomerbe.dto.RestaurantDto;
import com.kcjcustomerbe.entity.Product;
import com.kcjcustomerbe.entity.Restaurant;
import org.mapstruct.*;

import java.util.List;

/**
 * Interface for mapping `Product` and `Restaurant` entities to their respective DTOs and vice versa.
 * Uses MapStruct library for mapping, which generates the implementation at compile time.
 *
 * Mapping is performed by matching the `source` and `target` fields as specified in each `@Mapping`.
 *
 * Unmapped fields are ignored due to `unmappedTargetPolicy = ReportingPolicy.IGNORE`.
 * Mapping for null properties are ignored due to `nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE`.
 *
 * This Mapper is automatically deployed by Spring, using components scanning.
 * The implementation of the methods in this interface is generated by MapStruct and should not be manually implemented.
 *
 * @author Ivan Bukrieiev
 * @since v1.0.0
 */
@Mapper(componentModel = MappingConstants.ComponentModel.SPRING,
      unmappedTargetPolicy = ReportingPolicy.IGNORE,
      nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface ProductMapper {

   /**
    * Maps a `Product` entity to a `ProductDto`.
    *
    * @param entity The `Product` entity to be mapped.
    * @return The mapped `ProductDto`. If the source `Product` entity is null, return null.
    */
   @Mapping(target = "id", source = "id")
   @Mapping(target = "name", source = "name")
   @Mapping(target = "description", source = "description")
   @Mapping(target = "price", source = "price")
   @Mapping(target = "imageUrl", source = "imageUrl")
   @Mapping(target = "isAvailable", source = "isAvailable")
   @Mapping(target = "restaurantDto", source = "restaurant")
   ProductDto mapToProductDto(Product entity);

   /**
    * Maps a `Restaurant` entity to a `RestaurantDto`.
    *
    * @param entity The `Restaurant` entity to be mapped.
    * @return The mapped `RestaurantDto`. If the source `Restaurant` entity is null, return null.
    */
   @Mappings({
         @Mapping(target = "id", source = "id"),
         @Mapping(target = "address", source = "address"),
         @Mapping(target = "phoneNumber", source = "phoneNumber"),
         @Mapping(target = "openingHours", source = "openingHours"),
         @Mapping(target = "cuisineType", source = "cuisineType"),
         @Mapping(target = "description", source = "description"),
         @Mapping(target = "isOpen", source = "isOpen"),
         @Mapping(target = "productsDto", ignore = true),
         @Mapping(target = "reviewsDto", ignore = true),
         @Mapping(target = "ordersDto", ignore = true)

   })
   RestaurantDto mapToRestaurantDto(Restaurant entity);

   /**
    * Maps a list of `Product` entities to a list of `ProductDto`.
    *
    * @param products The list of `Product` entities to be mapped.
    * @return The list of mapped `ProductDto`. If the source list is null or empty, return an empty list.
    */
   List<ProductDto> mapToProductsDto(List<Product> products);
}
